---
title: 커뮤니티 & 알림
---
erDiagram
    MEMBER ||--o{ REVIEW : "작성"
    PRODUCT ||--o{ REVIEW : "리뷰"

    MEMBER ||--o{ NOTICE : "작성"
    NOTICE ||--o{ NOTICE_LIKE : "좋아요"
    MEMBER ||--o{ NOTICE_LIKE : "좋아요"

    MEMBER ||--o{ NOTIFICATION : "수신"
